services:
  chatsentinel:
    build: .
    container_name: chatsentinel
    restart: always
    env_file:
      - .env
    volumes:
      - ./wwebjs_auth:/app/.wwebjs_auth
    # ports:
    #   - '3000:3000'
